# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
logging:
  file:
    name: "kse-backend"
    path: "/opt/log"
