# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
logging:
  file:
    name: "kse-backend"
    path: "/var/log"
