# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
logging:
  file:
    name: "kse-frontend"
    path: "/opt/log"

# ----------------------------------------------------------------------------------------------------------------------
# Carnival
# ----------------------------------------------------------------------------------------------------------------------
carnival:
  openfeign:
    logger-level: basic
