# ----------------------------------------------------------------------------------------------------------------------
# Carnival
# ----------------------------------------------------------------------------------------------------------------------
carnival:
  openfeign:
    logger-level: full
