# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
logging:
  file:
    name: "kse-frontend"
    path: "/home/spring/log"
